function readonlyRuntimeHelpersSection(): string {
  return [
    "function buildShortcut(event){const parts=[];if(event.ctrlKey)parts.push('ctrl');if(event.metaKey)parts.push('meta');if(event.altKey)parts.push('alt');if(event.shiftKey)parts.push('shift');parts.push(String(event.key||'').toLowerCase());return parts.join('+');}",
    "function normalizeReadonlyText(value){return String(value||'').trim();}",
    "function normalizeReadonlyCommandId(value){const normalized=normalizeReadonlyText(value).toLowerCase();return normalized||null;}",
    "function normalizeReadonlyCommandUri(value){const normalized=normalizeReadonlyText(value);return normalized||null;}",
    "function normalizeReadonlyShortcut(value){return normalizeReadonlyText(value).toLowerCase().split('command').join('meta').split('cmd').join('meta').split('control').join('ctrl').replace(/\\s+/g,'')||null;}",
    "function decodeReadonlyUriComponent(value){try{return decodeURIComponent(value);}catch{return value;}}",
    "function parseReadonlyCommandUri(value){const normalized=normalizeReadonlyCommandUri(value);if(!normalized)return null;const match=/^([a-z0-9+.-]+):(.*)$/i.exec(normalized);if(!match)return null;const scheme=String(match[1]||'').toLowerCase();let commandId=null;if(scheme==='command'){const rawCommand=String(match[2]||'').replace(/^\\/\\//,'').split('?')[0]||'';commandId=normalizeReadonlyCommandId(decodeReadonlyUriComponent(rawCommand));}return{commandId,scheme,value:normalized};}",
    "function isReadonlyBlockedCommandId(commandId){const normalized=normalizeReadonlyCommandId(commandId);if(!normalized)return null;if(readonlyPolicy.blockedCommandIds.some(function(entry){return String(entry).toLowerCase()===normalized;}))return 'command \"'+commandId+'\" is blocked';if(readonlyPolicy.blockedCommandPrefixes.some(function(entry){return normalized.indexOf(String(entry).toLowerCase())===0;}))return 'command \"'+commandId+'\" matches a blocked prefix';if(readonlyPolicy.blockedCommandSubstrings.some(function(entry){return normalized.indexOf(String(entry).toLowerCase())>=0;}))return 'command \"'+commandId+'\" matches a blocked pattern';return null;}",
    "function isReadonlyBlockedSelector(selector){const normalized=normalizeReadonlyText(selector).toLowerCase();if(!normalized)return null;const match=readonlyPolicy.browserGuards.blockedSelectors.find(function(entry){return normalized.indexOf(String(entry).toLowerCase())>=0;});return match?'selector \"'+selector+'\" matches a blocked UI target':null;}",
    "function isReadonlyBlockedLabel(label){const normalized=normalizeReadonlyText(label).toLowerCase();if(!normalized)return null;const match=readonlyPolicy.browserGuards.blockedUiLabels.find(function(entry){return normalized.indexOf(String(entry).toLowerCase())>=0;});return match?'label \"'+label+'\" matches a blocked UI label':null;}",
    "function resolveReadonlyActionReason(action){if(!readonlyPolicy.enabled)return null;if(action.kind==='beforeinput'&&readonlyPolicy.browserGuards.blockBeforeInput)return 'editor input mutations are disabled in readonly sessions';if(action.kind==='drop'&&readonlyPolicy.browserGuards.blockDragAndDrop)return 'drag-and-drop is disabled in readonly sessions';if(action.kind==='paste'&&readonlyPolicy.browserGuards.blockPaste)return 'paste is disabled in readonly sessions';if(action.kind==='upload'&&readonlyPolicy.browserGuards.blockUpload)return 'uploads are disabled in readonly sessions';const parsed=parseReadonlyCommandUri(action.commandUri||action.href);if(parsed&&readonlyPolicy.browserGuards.blockedCommandLinkSchemes.some(function(entry){return String(entry).toLowerCase()===parsed.scheme;})){const commandReason=parsed.commandId?isReadonlyBlockedCommandId(parsed.commandId):null;if(commandReason)return 'command URI \"'+parsed.value+'\" '+commandReason.replace(/^command /,'activates command ');if(readonlyPolicy.browserGuards.blockCommandLinks)return parsed.commandId?'command URI \"'+parsed.value+'\" is blocked':'command link scheme \"'+parsed.scheme+':\" is blocked';}const commandReason=isReadonlyBlockedCommandId(action.commandId);if(commandReason)return commandReason;const shortcut=normalizeReadonlyShortcut(action.shortcut);if(shortcut&&readonlyPolicy.blockedShortcuts.some(function(entry){return normalizeReadonlyShortcut(entry)===shortcut;}))return 'shortcut \"'+action.shortcut+'\" is blocked';const selectorReason=isReadonlyBlockedSelector(action.selector);if(selectorReason)return selectorReason;const labelReason=isReadonlyBlockedLabel(action.label);if(labelReason)return labelReason;return null;}",
    "function describeReadonlySource(target){if(!target||!target.closest)return 'unknown';if(target.closest('.notification-toast,.notification-list-item,.notifications-toasts'))return 'notification';if(target.closest('.monaco-menu,.context-view'))return 'context-menu';if(target.closest('.monaco-action-bar,.monaco-button,.editor-widget,.zone-widget'))return 'widget';if(target.closest('.quick-input-widget,.quick-input-list'))return 'command-palette';if(target.closest('#__trebired_code_server_readonly_banner__'))return 'banner';if(target.closest('a,[href],[data-href]'))return 'link';return 'unknown';}",
    "function describeReadonlySelector(target){if(!target||!target.tagName)return null;const tag=String(target.tagName||'').toLowerCase();if(target.id)return tag+'#'+target.id;const className=typeof target.className==='string'?target.className.trim().split(/\\s+/).filter(Boolean).slice(0,3).join('.'):'';return className?tag+'.'+className:tag;}",
    "function extractReadonlyAction(target,defaults){const element=target&&target.closest?target.closest('[data-command],[href],[data-href],button,[role=\"button\"],input,textarea,*'):target;if(!element)return Object.assign({kind:'selector',source:'unknown'},defaults||{});const href=element.getAttribute&&((element.getAttribute('href')||element.getAttribute('data-href'))||null);const commandId=element.getAttribute&&(element.getAttribute('data-command')||element.getAttribute('command'))||null;const label=normalizeReadonlyText(element.getAttribute&&(element.getAttribute('aria-label')||element.getAttribute('title'))||(element.textContent||''))||null;const action={attributeName:commandId?'data-command':href?(String(href).indexOf('command:')===0?'href':'data-href'):null,commandId:commandId||null,commandUri:href&&String(href).indexOf('command:')===0?href:null,href:href||null,kind:(defaults&&defaults.kind)||'selector',label,selector:describeReadonlySelector(element),source:describeReadonlySource(element),shortcut:(defaults&&defaults.shortcut)||null};return Object.assign(action,defaults||{});}",
    "function blockReadonlyEvent(event,action){const reason=resolveReadonlyActionReason(action);if(!reason)return false;event.preventDefault();event.stopPropagation();if(typeof event.stopImmediatePropagation==='function')event.stopImmediatePropagation();emitReadonlyBlocked(action.kind,Object.assign({reason},action));return true;}",
    "function patchReadonlyLinkClicks(){if(typeof HTMLAnchorElement!=='function'||typeof HTMLAnchorElement.prototype.click!=='function')return;const nativeClick=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){const action=extractReadonlyAction(this,{kind:'command-uri',source:'link'});const reason=resolveReadonlyActionReason(action);if(reason){emitReadonlyBlocked(action.kind,Object.assign({reason},action));return;}return nativeClick.call(this);};}",
    "function patchReadonlyWindowOpen(){if(typeof window.open!=='function')return;const nativeOpen=window.open.bind(window);window.open=function(url,target,features){const action={commandUri:typeof url==='string'?url:null,href:typeof url==='string'?url:null,kind:'command-uri',label:null,selector:null,source:'link'};const reason=resolveReadonlyActionReason(action);if(reason){emitReadonlyBlocked(action.kind,Object.assign({reason},action));return null;}return nativeOpen(url,target,features);};}",
  ].join("");
}

function readonlyInstallSection(): string {
  return [
    "function installReadonlyGuards(){if(!readonlyPolicy.enabled)return;window.__TREBIRED_CODE_SERVER_READONLY_POLICY__=readonlyPolicy;",
    "patchReadonlyLinkClicks();",
    "patchReadonlyWindowOpen();",
    "if(readonlyPolicy.browserGuards.showBanner){const renderBanner=function(){if(document.getElementById('__trebired_code_server_readonly_banner__'))return;const banner=document.createElement('div');banner.id='__trebired_code_server_readonly_banner__';banner.textContent=readonlyPolicy.browserGuards.readonlyMessage;banner.setAttribute('role','status');banner.style.cssText='position:fixed;top:0;left:0;right:0;z-index:2147483647;padding:6px 12px;background:#111827;color:#f9fafb;font:12px/1.4 sans-serif;text-align:center;pointer-events:none;opacity:.92';document.body.appendChild(banner);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderBanner,{once:true});else renderBanner();}",
    "window.addEventListener('keydown',function(event){const shortcut=buildShortcut(event);if(readonlyPolicy.blockedShortcuts.indexOf(shortcut)>=0){event.preventDefault();event.stopPropagation();if(typeof event.stopImmediatePropagation==='function')event.stopImmediatePropagation();emitReadonlyBlocked('shortcut',{reason:'shortcut \"'+shortcut+'\" is blocked',shortcut,source:'keyboard'});return;}if(event.key==='Enter'||event.key===' '){const action=extractReadonlyAction(event.target,{kind:'command'});blockReadonlyEvent(event,action);}},true);",
    "if(readonlyPolicy.browserGuards.blockDragAndDrop){const blockDrop=function(event){blockReadonlyEvent(event,{kind:'drop',source:'widget'});};window.addEventListener('dragover',blockDrop,true);window.addEventListener('drop',blockDrop,true);}",
    "if(readonlyPolicy.browserGuards.blockPaste){window.addEventListener('paste',function(event){blockReadonlyEvent(event,{kind:'paste',source:'widget'});},true);}",
    "if(readonlyPolicy.browserGuards.blockBeforeInput){window.addEventListener('beforeinput',function(event){const inputType=String(event&&event.inputType||'');if(!inputType||/^insert|^delete|^history/i.test(inputType)){blockReadonlyEvent(event,{kind:'beforeinput',label:inputType||null,source:'widget'});}},true);}",
    "if(readonlyPolicy.browserGuards.blockUpload){window.addEventListener('change',function(event){const target=event.target;if(target&&target.matches&&target.matches(\"input[type='file']\")){target.value='';blockReadonlyEvent(event,{kind:'upload',selector:\"input[type='file']\",source:'widget'});}},true);}",
    "const clickHandler=function(event){const action=extractReadonlyAction(event.target,{kind:'command'});blockReadonlyEvent(event,action);};",
    "window.addEventListener('auxclick',clickHandler,true);",
    "window.addEventListener('click',clickHandler,true);",
    "window.addEventListener('submit',function(event){const target=event.target;if(target&&target.querySelector&&target.querySelector(\"input[type='file']\")){blockReadonlyEvent(event,{kind:'upload',selector:'form',source:'widget'});}},true);",
    "}",
  ].join("");
}

export {
  readonlyInstallSection,
  readonlyRuntimeHelpersSection,
};
